---
- name: Install filebeat
  hosts: web_servers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg, apt-transport-https
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Get filebeat 7.4.0
      ansible.builtin.get_url:
        url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-7.4.0-amd64.deb
        dest: /home/marakin/

    - name: Install filebeat
      apt:
        deb: /home/amrakin/filebeat-7.4.0-amd64.deb 

    - name: Copy config file for filebeat
      copy:
        src: ./elasticsearch_files/filebeat.yml
        dest: /etc/filebeat
        mode: 0600
        owner: root
        group: root

    - name: Systemctl daemon reload
      systemd:
        daemon_reload: true
        name: filebeat.service
        state: started

    - name: restarted nginx    
      service:
        name: nginx
        state: restarted

    - name: restarted filebeat   
      service:
        name: filebeat.service
        state: restarted

    - name: Systemctl enable filebeat
      ansible.builtin.service:
        name: filebeat.service
        enabled: yes